name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Instalar dependências
      run: npm install
      working-directory: ./
    - name: Executar testes
      run: npm test || echo "Nenhum teste definido ainda"
      working-directory: ./
